/**
 * Build check (spec L809-L822; FX17): the console's share of first load is its registrations, the drawer's frame
 * and the summary line. The body (the Log, the command line, the code tabs, the Export menu's items and what the
 * console's commands run) is a lazy chunk of its own, and the exporters another. Builds the app with its own
 * Vite config into a scratch directory, then reads what the first load fetches (the entry script and its module
 * preloads, from `index.html`) and what the lazy chunks carry.
 */
import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { mkdtempSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { build } from "vite";
import { appDir } from "../../../local-env";

/** The frame's own words: the toggle's names. Present at first load, or the test reads the wrong files. */
const FRAME_MARKERS = ["Collapse console", "Expand console"];
/** Strings only the body carries: LogView's (JUMP_TO_LATEST, NO_MATCH) and `help`'s, which a command reaches. */
const BODY_MARKERS = ["Jump to latest", "No lines match the filter.", "Type help <verb> for one."];
/** The Foundry exporter's header line (core's `exportFoundry`): in the exporters' chunk only. */
const EXPORTER_MARKERS = ["Generated by Lattice Studio"];

let out = "";
let firstLoad = "";
let lazy: { name: string; text: string }[] = [];

beforeAll(async () => {
  out = mkdtempSync(join(tmpdir(), "studio-console-entry-"));
  await build({ configFile: join(appDir, "vite.config.ts"), logLevel: "silent", build: { outDir: out, emptyOutDir: true } });
  const html = readFileSync(join(out, "index.html"), "utf8");
  const first = [...html.matchAll(/(?:src|href)="\.?\/?(assets\/[^"]+\.js)"/g)].map((m) => m[1] ?? "");
  expect(first.length).toBeGreaterThan(0);
  firstLoad = first.map((path) => readFileSync(join(out, path), "utf8")).join("\n");
  lazy = readdirSync(join(out, "assets"))
    .filter((name) => name.endsWith(".js") && !first.includes(`assets/${name}`))
    .map((name) => ({ name, text: readFileSync(join(out, "assets", name), "utf8") }));
}, 120_000);

afterAll(() => {
  if (out) rmSync(out, { recursive: true, force: true });
});

function inFirstLoad(markers: readonly string[]): { marker: string; found: boolean }[] {
  return markers.map((marker) => ({ marker, found: firstLoad.includes(marker) }));
}

describe("the console in the entry chunk", () => {
  test("the drawer's frame paints with the first load", () => {
    expect(inFirstLoad(FRAME_MARKERS)).toEqual(FRAME_MARKERS.map((marker) => ({ marker, found: true })));
  });

  test("the body is absent from first load", () => {
    expect(inFirstLoad(BODY_MARKERS)).toEqual(BODY_MARKERS.map((marker) => ({ marker, found: false })));
  });

  test("a lazy chunk named for the body carries it", () => {
    const body = lazy.find((chunk) => chunk.name.startsWith("body-"));
    expect(body).toBeDefined();
    for (const marker of BODY_MARKERS) expect({ marker, found: body?.text.includes(marker) }).toEqual({ marker, found: true });
  });

  test("the exporters are one chunk of their own, in neither the entry nor the body", () => {
    const body = lazy.find((chunk) => chunk.name.startsWith("body-"));
    const exporters = lazy.filter((chunk) => EXPORTER_MARKERS.every((marker) => chunk.text.includes(marker)));
    expect(exporters.map((chunk) => chunk.name.replace(/-[\w-]+\.js$/, ""))).toEqual(["exporters"]);
    for (const marker of EXPORTER_MARKERS) {
      expect({ marker, entry: firstLoad.includes(marker), body: body?.text.includes(marker) }).toEqual({ marker, entry: false, body: false });
    }
  });
});
