import type { ExportFile } from "@lattice-studio/core";
import { exportBrief, exportFoundry, exportRecipeJson, exportSafeBatch } from "@lattice-studio/core";
import { beforeEach, describe, expect, test, vi } from "vitest";
import { page, userEvent } from "vitest/browser";
import {
  doc, getAnalysis, getCatalog, provideDeployController, provideServices, runCommand, session, type DeployController,
} from "@/contracts";
import { DialogHost } from "@/ui/overlays/DialogHost";
import { axeViolations } from "@/ui/testing/axe";
import studio from "../../../package.json" with { type: "json" };
import { bufferedServices, onCleanup, renderWithStudio } from "../../../test/harness";
import { scriptChainIds } from "./chains";
import { ConsolePanel } from "./ConsolePanel";
import { downloadFile } from "./download";
import { logEntries } from "./log-store";
import { DOWNLOAD_BATCH, NOT_AN_ADDRESS, SAFE_ADDRESS_LABEL } from "./SafeBatchDialog";
import { captureDownloads, collisionProject, erc20Project, resetConsole } from "./test-support";

beforeEach(() => resetConsole());

const SAFE = "0x71C7656EC7ab88b098defB751B7401B5f6d8976F" as const;

async function renderConsole(project = erc20Project(), theme: "shop" | "draft" = "shop", chainId: number | null = null) {
  return renderWithStudio(
    <>
      <div style={{ height: "600px", display: "flex" }}>
        <ConsolePanel />
      </div>
      <DialogHost />
    </>,
    { project, theme, session: { chainId } },
  );
}

const exportMenu = () => page.getByRole("button", { name: "Export", exact: true });
const item = (name: string) => page.getByRole("menuitem", { name });
const reasonOf = (name: string) => {
  const el = item(name).element();
  const id = el.getAttribute("aria-describedby");
  return id ? document.getElementById(id)?.textContent ?? null : null;
};

function catalog() {
  const c = getCatalog();
  if (!c) throw new Error("no catalog");
  return c;
}

async function waitForFile(files: ExportFile[], n = 1): Promise<ExportFile> {
  await vi.waitFor(() => expect(files.length).toBeGreaterThanOrEqual(n));
  return files[n - 1] as ExportFile;
}

describe("Export menu (spec L509-L518, IR L132)", () => {
  test("lists every export; Image arrives in v1.1; blockers disable the script and the Safe batch with the reason", async () => {
    await renderConsole(collisionProject());
    await userEvent.click(exportMenu());
    for (const name of ["Foundry script", "Agent brief", "Copy agent brief", "Recipe JSON", "Project file", "Safe batch…", "Image"]) {
      await expect.element(item(name)).toBeVisible();
    }
    expect(reasonOf("Image")).toBe("Arrives in v1.1");
    expect(reasonOf("Foundry script")).toBe("Resolve 2 blockers to export · F8");
    expect(reasonOf("Safe batch…")).toBe("Resolve 2 blockers to export · F8");
    expect(reasonOf("Agent brief")).toBeNull();
    expect(reasonOf("Recipe JSON")).toBeNull();
    // S7b owns the project file; until it lands the item says so.
    expect(reasonOf("Project file") ?? "").toMatch(/^Not built yet · WP-S7b$|^$/);
  });

  test("Foundry script opens the Script tab maximized; Download saves core's file byte for byte, headed as spec L508 says", async () => {
    const files = captureDownloads();
    await renderConsole();
    await userEvent.click(exportMenu());
    await userEvent.click(item("Foundry script"));
    await vi.waitFor(() => expect(session.get().panes.console).toMatchObject({ tab: "script", maximized: true }));
    await expect.element(page.getByText("DeployERC20.s.sol")).toBeVisible();
    await userEvent.click(page.getByRole("button", { name: "Download" }));
    const file = await waitForFile(files);
    const expected = exportFoundry({
      project: doc.get(), catalog: catalog(), analysis: getAnalysis(), studioVersion: studio.version, chainIds: scriptChainIds(catalog()),
    });
    if (!expected.ok) throw new Error(expected.error);
    expect(file).toEqual(expected.value);
    expect(file.filename).toBe("DeployERC20.s.sol");
    expect(file.text).toContain(`Generated by Lattice Studio ${studio.version}.`);
    expect(file.text).toContain(`// Recipe hash: ${getAnalysis().recipeHash}`);
    expect(file.text).toContain("// Catalog: Lattice fixture");
    expect(file.text).toContain("// Chains: 84532, 11155111");
    const exported = logEntries().at(-1);
    expect(exported?.text).toMatch(/^Exported DeployERC20\.s\.sol · recipe 0x[0-9a-f]{4}…[0-9a-f]{4}$/);
  });

  test("Agent brief downloads core's .brief.md; Copy agent brief copies it", async () => {
    const writeText = vi.spyOn(navigator.clipboard, "writeText").mockResolvedValue(undefined);
    onCleanup(() => writeText.mockRestore());
    const files = captureDownloads();
    await renderConsole();
    await userEvent.click(exportMenu());
    await userEvent.click(item("Agent brief"));
    const file = await waitForFile(files);
    const expected = exportBrief({ recipe: doc.get().recipe, catalog: catalog(), analysis: getAnalysis(), studioVersion: studio.version });
    expect(file).toEqual(expected);
    expect(file.filename).toBe("erc20.brief.md");
    expect(file.mime).toBe("text/markdown");
    expect(file.text.split("\n")[0]).toBe("# ERC20 agent brief");
    expect(file.text).toContain(`Recipe hash: \`${getAnalysis().recipeHash}\``);
    await userEvent.click(exportMenu());
    await userEvent.click(item("Copy agent brief"));
    await vi.waitFor(() => expect(writeText).toHaveBeenCalledWith(expected.text));
    expect(bufferedServices().toast.at(-1)).toEqual({ text: "Copied erc20.brief.md" });
  });

  test("Recipe JSON opens its tab; Copy and Download give recipe.json with $schema, byte for byte", async () => {
    const writeText = vi.spyOn(navigator.clipboard, "writeText").mockResolvedValue(undefined);
    onCleanup(() => writeText.mockRestore());
    const files = captureDownloads();
    await renderConsole();
    await userEvent.click(exportMenu());
    await userEvent.click(item("Recipe JSON"));
    await vi.waitFor(() => expect(session.get().panes.console.tab).toBe("recipe"));
    await expect.element(page.getByText("recipe.json", { exact: true })).toBeVisible();
    const expected = exportRecipeJson(doc.get().recipe, catalog());
    await userEvent.click(page.getByRole("button", { name: "Copy" }));
    await vi.waitFor(() => expect(writeText).toHaveBeenCalledWith(expected.text));
    await userEvent.click(page.getByRole("button", { name: "Download" }));
    const file = await waitForFile(files);
    expect(file).toEqual(expected);
    expect(JSON.parse(file.text).$schema).toMatch(/recipe\.v1\.json$/);
  });

  test("Safe batch asks for the Safe and chain, downloads the batch and records it as Proposed", async () => {
    const proposals: Parameters<DeployController["proposed"]>[0][] = [];
    const controller = {
      state: () => ({ phase: "idle" as const }), subscribe: () => () => {}, open() {}, changed() {}, sign: async () => {},
      proposed: (batch: Parameters<DeployController["proposed"]>[0]) => void proposals.push(batch),
      deployMissing: async () => {}, keepWaiting() {}, checkWallet() {}, reviewAgain() {}, discardProposal() {}, retry() {}, close() {},
    } satisfies DeployController;
    onCleanup(provideDeployController(async () => controller));
    onCleanup(provideServices({ now: () => Date.parse("2026-09-23T12:00:00Z") }));
    const files = captureDownloads();
    await renderConsole(erc20Project(), "shop", 84532);
    await userEvent.click(exportMenu());
    await userEvent.click(item("Safe batch…"));
    const address = page.getByRole("textbox", { name: SAFE_ADDRESS_LABEL });
    await expect.element(address).toHaveFocus();
    await userEvent.click(page.getByRole("button", { name: DOWNLOAD_BATCH }));
    await expect.element(page.getByText(NOT_AN_ADDRESS)).toBeVisible();
    expect(files).toEqual([]);
    await userEvent.fill(address, SAFE.toLowerCase());
    await userEvent.click(page.getByRole("button", { name: DOWNLOAD_BATCH }));
    const file = await waitForFile(files);
    await vi.waitFor(() => expect(session.get().dialogs).toEqual([]));
    const expected = exportSafeBatch({
      recipe: doc.get().recipe, catalog: catalog(), safe: SAFE, chainId: 84532, entropy: doc.get().deploy.entropy,
      scope: doc.get().deploy.scope, path: doc.get().deploy.path, now: Date.parse("2026-09-23T12:00:00Z"),
      studioVersion: studio.version, context: { known: [], unconfirmed: [] },
    });
    if (!expected.ok) throw new Error(expected.error);
    expect(file).toEqual(expected.value);
    expect(file.filename).toMatch(/\.safe\.json$/);
    expect(JSON.parse(file.text)).toMatchObject({ version: "1.0", chainId: "84532" });
    await vi.waitFor(() => expect(proposals).toHaveLength(1));
    expect(proposals[0]).toMatchObject({ safe: SAFE, chainId: 84532 });
  });

  test("the Safe batch dialog closes with Cancel and changes nothing", async () => {
    const files = captureDownloads();
    await renderConsole();
    void runCommand({ id: "export.safe" }, "palette");
    await expect.element(page.getByRole("dialog", { name: "Safe batch" })).toBeVisible();
    await userEvent.click(page.getByRole("button", { name: "Cancel" }));
    await vi.waitFor(() => expect(session.get().dialogs).toEqual([]));
    expect(files).toEqual([]);
  });
});

describe("Script and Recipe JSON tabs (IR L135-L136)", () => {
  test("an empty sheet says how to get a script", async () => {
    const empty = erc20Project();
    await renderConsole({ ...empty, recipe: { ...empty.recipe, facets: [] } });
    await userEvent.click(page.getByRole("tab", { name: "Script" }));
    await expect.element(page.getByText("Place facets to generate a script.")).toBeVisible();
  });

  test("while blockers exist: a banner, and Copy and Download say why; the last script stays for reference", async () => {
    await renderConsole();
    await userEvent.click(page.getByRole("tab", { name: "Script" }));
    await expect.element(page.getByText("DeployERC20.s.sol")).toBeVisible();
    await runCommand({ id: "facet.place", args: { facet: "AxelarGatewayAdapter" } }, "console");
    await runCommand({ id: "facet.place", args: { facet: "HyperlaneGatewayAdapter" } }, "console");
    await expect.element(page.getByText("Resolve 2 blockers to export · F8").first()).toBeVisible();
    for (const name of ["Copy", "Download"]) {
      const button = page.getByRole("button", { name });
      expect(button.element().getAttribute("aria-disabled")).toBe("true");
    }
    await expect.element(page.getByText("DeployERC20.s.sol")).toBeVisible();
  });

  test("change marks show which lines changed since the last script", async () => {
    await renderConsole();
    await userEvent.click(page.getByRole("tab", { name: "Script" }));
    await expect.element(page.getByText("DeployERC20.s.sol")).toBeVisible();
    expect(document.querySelectorAll("[data-changed]")).toHaveLength(0);
    doc.apply("Rename", (p) => ({ project: { ...p, name: "Token" }, changed: true, summary: "Renamed" }));
    await expect.element(page.getByText("DeployToken.s.sol")).toBeVisible();
    await vi.waitFor(() => expect(document.querySelectorAll("[data-changed]").length).toBeGreaterThan(0));
    const changed = [...document.querySelectorAll("[data-changed]")].map((el) => el.textContent ?? "");
    expect(changed.every((t) => t.includes("changed: "))).toBe(true);
    expect(changed.some((t) => t.includes("DeployToken"))).toBe(true);
  });

  test("a real download goes through a Blob and a link with the file's name", async () => {
    const clicks: { name: string; href: string }[] = [];
    const click = vi.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(function (this: HTMLAnchorElement) {
      clicks.push({ name: this.download, href: this.href });
    });
    onCleanup(() => click.mockRestore());
    downloadFile({ filename: "recipe.json", mime: "application/json", text: "{}" });
    expect(clicks).toEqual([{ name: "recipe.json", href: expect.stringMatching(/^blob:/) }]);
  });

  for (const theme of ["shop", "draft"] as const) {
    test(`the Script tab has no axe violations, in ${theme}`, async () => {
      await renderConsole(erc20Project(), theme);
      await userEvent.click(page.getByRole("tab", { name: "Script" }));
      await expect.element(page.getByText("DeployERC20.s.sol")).toBeVisible();
      await vi.waitFor(() => expect(document.querySelector("pre[data-highlighted]")).not.toBeNull(), { timeout: 5000 });
      expect(await axeViolations(document.body)).toEqual([]);
    });
  }
});
