import type { ExportFile, Problem } from "@lattice-studio/core";
import { exportBrief, exportFoundry, exportRecipeJson, exportSafeBatch, loadTemplate } from "@lattice-studio/core";
import { makeProject } from "@lattice-studio/core/testing";
import { beforeEach, describe, expect, test, vi } from "vitest";
import { page, userEvent } from "vitest/browser";
import {
  doc, emptyAnalysis, getAnalysis, getCatalog, initialSession, provideDeployController, provideServices, runCommand,
  session, type DeployController,
} from "@/contracts";
import { DialogHost } from "@/ui/overlays/DialogHost";
import { axeViolations } from "@/ui/testing/axe";
import studio from "../../../package.json" with { type: "json" };
import { bufferedServices, fixtureCatalog, onCleanup, renderWithStudio } from "../../../test/harness";
import { scriptChainIds } from "./chains";
import { ConsolePanel } from "./ConsolePanel";
import { downloadFile } from "./download";
import { S5E_COMMANDS } from "./definitions";
import { safeExportable } from "./export-enablement";
import { logEntries } from "./log-store";
import { DOWNLOAD_BATCH, NOT_AN_ADDRESS, SAFE_ADDRESS_LABEL } from "./SafeBatchDialog";
import { awaitConsoleBody, captureDownloads, collisionProject, erc20Project, resetConsole } from "./test-support";

beforeEach(() => resetConsole());

const SAFE = "0x71C7656EC7ab88b098defB751B7401B5f6d8976F" as const;

async function renderConsole(project = erc20Project(), theme: "shop" | "draft" = "shop", chainId: number | null = null) {
  const rendered = await renderWithStudio(
    <>
      <div style={{ height: "600px", display: "flex" }}>
        <ConsolePanel />
      </div>
      <DialogHost />
    </>,
    { project, theme, session: { chainId } },
  );
  await awaitConsoleBody();
  return rendered;
}

const exportMenu = () => page.getByRole("button", { name: "Export", exact: true });
const item = (name: string) => page.getByRole("menuitem", { name });
const reasonOf = (name: string) => {
  const el = item(name).element();
  const id = el.getAttribute("aria-describedby");
  return id ? document.getElementById(id)?.textContent ?? null : null;
};

function catalog() {
  const c = getCatalog();
  if (!c) throw new Error("no catalog");
  return c;
}

async function waitForFile(files: ExportFile[], n = 1): Promise<ExportFile> {
  await vi.waitFor(() => expect(files.length).toBeGreaterThanOrEqual(n));
  return files[n - 1] as ExportFile;
}

/** The Safe batch waits for the review's acknowledgements (spec L573): tick every one the analysis raises. */
function tickAcknowledgements(): void {
  const analysis = getAnalysis();
  const ids = analysis.problems.filter((p) => p.ack === true).map((p) => p.id);
  session.set({ acks: { ...session.get().acks, [analysis.recipeHash]: ids } });
}

describe("Export menu (spec L509-L518, IR L132)", () => {
  test("lists every export; Image arrives in v1.1; blockers disable the script and the Safe batch with the reason", async () => {
    await renderConsole(collisionProject());
    await userEvent.click(exportMenu());
    for (const name of ["Foundry script", "Agent brief", "Copy agent brief", "Recipe JSON", "Project file", "Safe batch…", "Image"]) {
      await expect.element(item(name)).toBeVisible();
    }
    expect(reasonOf("Image")).toBe("Arrives in v1.1");
    expect(reasonOf("Foundry script")).toBe("Resolve 2 blockers to export · F8");
    expect(reasonOf("Safe batch…")).toBe("Resolve 2 blockers to export · F8");
    expect(reasonOf("Agent brief")).toBeNull();
    expect(reasonOf("Recipe JSON")).toBeNull();
    // S7b owns the project file; until it lands the item says so.
    expect(reasonOf("Project file") ?? "").toMatch(/^Not built yet · WP-S7b$|^$/);
  });

  test("Foundry script opens the Script tab maximized; Download saves core's file byte for byte, headed as spec L508 says", async () => {
    const files = captureDownloads();
    await renderConsole();
    await userEvent.click(exportMenu());
    await userEvent.click(item("Foundry script"));
    await vi.waitFor(() => expect(session.get().panes.console).toMatchObject({ tab: "script", maximized: true }));
    await expect.element(page.getByText("DeployERC20.s.sol")).toBeVisible();
    await userEvent.click(page.getByRole("button", { name: "Download" }));
    const file = await waitForFile(files);
    const expected = exportFoundry({
      project: doc.get(), catalog: catalog(), analysis: getAnalysis(), studioVersion: studio.version, chainIds: scriptChainIds(catalog()),
    });
    if (!expected.ok) throw new Error(expected.error);
    expect(file).toEqual(expected.value);
    expect(file.filename).toBe("DeployERC20.s.sol");
    expect(file.text).toContain(`Generated by Lattice Studio ${studio.version}.`);
    expect(file.text).toContain(`// Recipe hash: ${getAnalysis().recipeHash}`);
    expect(file.text).toContain("// Catalog: Lattice fixture");
    expect(file.text).toContain("// Chains: 84532, 11155111");
    const exported = logEntries().at(-1);
    expect(exported?.text).toMatch(/^Exported DeployERC20\.s\.sol · recipe 0x[0-9a-f]{4}…[0-9a-f]{4}$/);
  });

  test("Agent brief downloads core's .brief.md; Copy agent brief copies it", async () => {
    const writeText = vi.spyOn(navigator.clipboard, "writeText").mockResolvedValue(undefined);
    onCleanup(() => writeText.mockRestore());
    const files = captureDownloads();
    await renderConsole();
    await userEvent.click(exportMenu());
    await userEvent.click(item("Agent brief"));
    const file = await waitForFile(files);
    const expected = exportBrief({ recipe: doc.get().recipe, catalog: catalog(), analysis: getAnalysis(), studioVersion: studio.version });
    expect(file).toEqual(expected);
    expect(file.filename).toBe("erc20.brief.md");
    expect(file.mime).toBe("text/markdown");
    expect(file.text.split("\n")[0]).toBe("# ERC20 agent brief");
    expect(file.text).toContain(`Recipe hash: \`${getAnalysis().recipeHash}\``);
    await userEvent.click(exportMenu());
    await userEvent.click(item("Copy agent brief"));
    await vi.waitFor(() => expect(writeText).toHaveBeenCalledWith(expected.text));
    expect(bufferedServices().toast.at(-1)).toEqual({ text: "Copied erc20.brief.md" });
  });

  test("Recipe JSON opens its tab; Copy and Download give recipe.json with $schema, byte for byte", async () => {
    const writeText = vi.spyOn(navigator.clipboard, "writeText").mockResolvedValue(undefined);
    onCleanup(() => writeText.mockRestore());
    const files = captureDownloads();
    await renderConsole();
    await userEvent.click(exportMenu());
    await userEvent.click(item("Recipe JSON"));
    await vi.waitFor(() => expect(session.get().panes.console.tab).toBe("recipe"));
    await expect.element(page.getByText("recipe.json", { exact: true })).toBeVisible();
    const expected = exportRecipeJson(doc.get().recipe, catalog());
    await userEvent.click(page.getByRole("button", { name: "Copy" }));
    await vi.waitFor(() => expect(writeText).toHaveBeenCalledWith(expected.text));
    await userEvent.click(page.getByRole("button", { name: "Download" }));
    const file = await waitForFile(files);
    expect(file).toEqual(expected);
    expect(JSON.parse(file.text).$schema).toMatch(/recipe\.v1\.json$/);
  });

  test("Safe batch asks for the Safe and chain, downloads the batch and records it as Proposed", async () => {
    const proposals: Parameters<DeployController["proposed"]>[0][] = [];
    const controller = {
      state: () => ({ phase: "idle" as const }), subscribe: () => () => {}, open() {}, changed() {}, sign: async () => {},
      proposed: (batch: Parameters<DeployController["proposed"]>[0]) => void proposals.push(batch),
      deployMissing: async () => {}, keepWaiting() {}, checkWallet() {}, reviewAgain() {}, discardProposal() {}, retry() {}, close() {},
    } satisfies DeployController;
    onCleanup(provideDeployController(async () => controller));
    onCleanup(provideServices({ now: () => Date.parse("2026-09-23T12:00:00Z") }));
    const files = captureDownloads();
    await renderConsole(erc20Project(), "shop", 84532);
    tickAcknowledgements();
    await userEvent.click(exportMenu());
    await userEvent.click(item("Safe batch…"));
    const address = page.getByRole("textbox", { name: SAFE_ADDRESS_LABEL });
    await expect.element(address).toHaveFocus();
    await userEvent.click(page.getByRole("button", { name: DOWNLOAD_BATCH }));
    await expect.element(page.getByText(NOT_AN_ADDRESS)).toBeVisible();
    expect(files).toEqual([]);
    await userEvent.fill(address, SAFE.toLowerCase());
    await userEvent.click(page.getByRole("button", { name: DOWNLOAD_BATCH }));
    const file = await waitForFile(files);
    await vi.waitFor(() => expect(session.get().dialogs).toEqual([]));
    const expected = exportSafeBatch({
      recipe: doc.get().recipe, catalog: catalog(), safe: SAFE, chainId: 84532, entropy: doc.get().deploy.entropy,
      scope: doc.get().deploy.scope, path: doc.get().deploy.path, now: Date.parse("2026-09-23T12:00:00Z"),
      studioVersion: studio.version, context: { known: [], unconfirmed: [] },
    });
    if (!expected.ok) throw new Error(expected.error);
    expect(file).toEqual(expected.value);
    expect(file.filename).toMatch(/\.safe\.json$/);
    expect(JSON.parse(file.text)).toMatchObject({ version: "1.0", chainId: "84532" });
    await vi.waitFor(() => expect(proposals).toHaveLength(1));
    expect(proposals[0]).toMatchObject({ safe: SAFE, chainId: 84532 });
  });

  test("the Safe batch carries the project's context: a predicted address and a linked argument refuse it", async () => {
    const recipe = loadTemplate(fixtureCatalog(), "SafeDiamondCut");
    if (!recipe.ok) throw new Error(recipe.error);
    const predicted = "0x5FbDB2315678afecb367f032d93F642f64180aa3" as const;
    const linked = "0x1234567890123456789012345678901234567890" as const;
    const init = recipe.value.init;
    if (init.kind !== "steps" || !init.steps[0]) throw new Error("SafeDiamondCut has steps");
    const step = { ...init.steps[0], args: { ...init.steps[0].args, safe: linked, admin: predicted } };
    const project = makeProject({
      id: "p-safe", name: "Safe cut",
      recipe: { ...recipe.value, init: { ...init, steps: [step] } },
      predicted: [{ chainId: 84532, address: predicted }],
      provenance: { "steps[0].safe": "link" },
    });
    await renderConsole(project);
    const now = Date.parse("2026-09-23T12:00:00Z");
    const { safeBatch } = await import("./exporters/safe");
    const built = await safeBatch({ project: doc.get(), catalog: catalog(), safe: SAFE, chainId: 84532, now });
    // Without the context the same inputs would build; with it, AUTH-02 and LINK-01 refuse the batch.
    const bare = exportSafeBatch({
      recipe: doc.get().recipe, catalog: catalog(), safe: SAFE, chainId: 84532, entropy: doc.get().deploy.entropy,
      scope: doc.get().deploy.scope, path: doc.get().deploy.path, now, studioVersion: studio.version,
    });
    expect(bare.ok).toBe(true);
    expect(built.ok).toBe(false);
    if (built.ok) return;
    expect(built.error).toMatch(/^Resolve \d+ blockers? to export: .*AUTH-02/);
    expect(built.error).toMatch(/LINK-01/);
  });

  test("the Safe batch dialog closes with Cancel and changes nothing", async () => {
    const files = captureDownloads();
    await renderConsole();
    tickAcknowledgements();
    void runCommand({ id: "export.safe" }, "palette");
    await expect.element(page.getByRole("dialog", { name: "Safe batch" })).toBeVisible();
    await userEvent.click(page.getByRole("button", { name: "Cancel" }));
    await vi.waitFor(() => expect(session.get().dialogs).toEqual([]));
    expect(files).toEqual([]);
  });
});

describe("Script and Recipe JSON tabs (IR L135-L136)", () => {
  test("an empty sheet says how to get a script", async () => {
    const empty = erc20Project();
    await renderConsole({ ...empty, recipe: { ...empty.recipe, facets: [] } });
    await userEvent.click(page.getByRole("tab", { name: "Script" }));
    await expect.element(page.getByText("Place facets to generate a script.")).toBeVisible();
  });

  test("while blockers exist: a banner, and Copy and Download say why; the last script stays for reference", async () => {
    await renderConsole();
    await userEvent.click(page.getByRole("tab", { name: "Script" }));
    await expect.element(page.getByText("DeployERC20.s.sol")).toBeVisible();
    await runCommand({ id: "facet.place", args: { facet: "AxelarGatewayAdapter" } }, "console");
    await runCommand({ id: "facet.place", args: { facet: "HyperlaneGatewayAdapter" } }, "console");
    await expect.element(page.getByText("Resolve 2 blockers to export · F8").first()).toBeVisible();
    for (const name of ["Copy", "Download"]) {
      const button = page.getByRole("button", { name });
      expect(button.element().getAttribute("aria-disabled")).toBe("true");
    }
    await expect.element(page.getByText("DeployERC20.s.sol")).toBeVisible();
  });

  test("change marks show which lines changed since the last script", async () => {
    await renderConsole();
    await userEvent.click(page.getByRole("tab", { name: "Script" }));
    await expect.element(page.getByText("DeployERC20.s.sol")).toBeVisible();
    expect(document.querySelectorAll("[data-changed]")).toHaveLength(0);
    doc.apply("Rename", (p) => ({ project: { ...p, name: "Token" }, changed: true, summary: "Renamed" }));
    await expect.element(page.getByText("DeployToken.s.sol")).toBeVisible();
    await vi.waitFor(() => expect(document.querySelectorAll("[data-changed]").length).toBeGreaterThan(0));
    const changed = [...document.querySelectorAll("[data-changed]")].map((el) => el.textContent ?? "");
    expect(changed.every((t) => t.includes("changed: "))).toBe(true);
    expect(changed.some((t) => t.includes("DeployToken"))).toBe(true);
  });

  test("a real download goes through a Blob and a link with the file's name", async () => {
    const clicks: { name: string; href: string }[] = [];
    const click = vi.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(function (this: HTMLAnchorElement) {
      clicks.push({ name: this.download, href: this.href });
    });
    onCleanup(() => click.mockRestore());
    downloadFile({ filename: "recipe.json", mime: "application/json", text: "{}" });
    expect(clicks).toEqual([{ name: "recipe.json", href: expect.stringMatching(/^blob:/) }]);
  });

  for (const theme of ["shop", "draft"] as const) {
    test(`the Script tab has no axe violations, in ${theme}`, async () => {
      await renderConsole(erc20Project(), theme);
      await userEvent.click(page.getByRole("tab", { name: "Script" }));
      await expect.element(page.getByText("DeployERC20.s.sol")).toBeVisible();
      await vi.waitFor(() => expect(document.querySelector("pre[data-highlighted]")).not.toBeNull(), { timeout: 5000 });
      expect(await axeViolations(document.body)).toEqual([]);
    });
  }
});

describe("safeExportable: the Safe batch waits for the review's acknowledgements (spec L573)", () => {
  const acknowledgement: Problem = {
    id: "CORE-02:0xdeadbeef", code: "CORE-02", severity: "warning", where: [], params: {}, message: "", ack: true, fixes: [],
  };
  const fixture = fixtureCatalog();
  const project = erc20Project();
  const analysis = { ...emptyAnalysis(), recipeHash: "0xabc" as const, problems: [acknowledgement] };

  test("disabled with the same reason as deploy.downloadSafeBatch while it's unticked", () => {
    const result = safeExportable({ catalog: fixture, project, analysis, session: initialSession() });
    expect(result).toEqual({ ok: false, reason: "Tick the acknowledgement first" });
  });

  test("several unticked acknowledgements are counted", () => {
    const second: Problem = { ...acknowledgement, id: "INIT-05:0xfeedface", code: "INIT-05" };
    const result = safeExportable({
      catalog: fixture, project, analysis: { ...analysis, problems: [acknowledgement, second] }, session: initialSession(),
    });
    expect(result).toEqual({ ok: false, reason: "Tick the 2 acknowledgements first" });
  });

  test("the export.safe command itself gates on them (the console verb and Export ▸ Safe batch)", () => {
    const safe = S5E_COMMANDS.find((c) => c.id === "export.safe");
    const ctx = { catalog: fixture, project, analysis, session: initialSession() } as unknown as Parameters<NonNullable<typeof safe>["enabled"]>[0];
    expect(safe?.enabled(ctx, {})).toEqual({ ok: false, reason: "Tick the acknowledgement first" });
  });

  test("once ticked for this recipe hash, it exports as before", () => {
    const ticked = { ...initialSession(), acks: { "0xabc": [acknowledgement.id] } };
    expect(safeExportable({ catalog: fixture, project, analysis, session: ticked })).toEqual({ ok: true });
  });

  test("a tick for a different recipe hash doesn't count", () => {
    const ticked = { ...initialSession(), acks: { "0xother": [acknowledgement.id] } };
    expect(safeExportable({ catalog: fixture, project, analysis, session: ticked }))
      .toEqual({ ok: false, reason: "Tick the acknowledgement first" });
  });

  test("deployableExport's own gates still apply first: no facets, then blockers", () => {
    const empty = { ...analysis, problems: [] };
    const noFacets = { ...project, recipe: { ...project.recipe, facets: [] } };
    expect(safeExportable({ catalog: fixture, project: noFacets, analysis: empty, session: initialSession() }))
      .toEqual({ ok: false, reason: "Place facets first" });
  });

  test("its own ack filter and wording agree with chain/review/model.ts's pendingAcks and entry-copy.ts's tickFirst (drift guard)", async () => {
    const { pendingAcks } = await import("@/chain/review/model");
    const { tickFirst } = await import("@/chain/review/entry-copy");
    const ticked: Problem = { id: "AUTH-01:0xabc", code: "AUTH-01", severity: "warning", where: [], params: {}, message: "", ack: true, fixes: [] };
    // A plain warning (no `ack`) never counts, in either module.
    const plain: Problem = { id: "CORE-04:diamond", code: "CORE-04", severity: "warning", where: [], params: {}, message: "", fixes: [] };
    const problems = [acknowledgement, ticked, plain];
    const acked = [ticked.id];
    const mixed = { ...analysis, problems };
    const mixedSession = { ...initialSession(), acks: { [mixed.recipeHash]: acked } };
    expect(safeExportable({ catalog: fixture, project, analysis: mixed, session: mixedSession }))
      .toEqual({ ok: false, reason: tickFirst(pendingAcks(problems, acked).length) });
  });
});
