// Renders dist/tokens.css: `:root[data-theme="shop"|"draft"]` role blocks,
// the (theme-independent) type scale, spacing, radius and stroke, and the
// `forced-colors` / `prefers-contrast` blocks (spec L785-L786).

import { LAYOUT_CSS_LENGTH_KEYS, layoutSizes } from "./layout.ts";
import { THEMES, themeRoles, type ThemeRoles } from "./roles.ts";
import type { TokensJson } from "./tokens-json.ts";

const ROLE_ORDER: readonly (keyof ThemeRoles)[] = [
  "ground",
  "groundWell",
  "panel",
  "raised",
  "sunken",
  "text",
  "textMuted",
  "textFaint",
  "border",
  "borderSubtle",
  "borderStrong",
  "borderFocus",
  "accent",
  "accentStrong",
  "onAccent",
  "accentSoft",
  "accentLine",
  "dot",
  "hatch",
];

export function kebab(name: string): string {
  return name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function themeBlock(theme: string, roles: ThemeRoles): string {
  const lines = ROLE_ORDER.map((key) => `  --lx-${kebab(key)}: ${roles[key]};`);
  return `:root[data-theme="${theme}"] {\n${lines.join("\n")}\n}`;
}

function baseBlock(json: TokensJson): string {
  const lines: string[] = [];
  lines.push(`  --lx-font-sans: ${json.fontFamilies.sans};`);
  lines.push(`  --lx-font-mono: ${json.fontFamilies.mono};`);
  for (const style of json.typeStyles) {
    const family = style.family === "sans" ? "var(--lx-font-sans)" : "var(--lx-font-mono)";
    lines.push(
      `  --lx-font-${style.name}: ${style.fontWeight} ${style.fontSize}/${style.lineHeight} ${family};`,
    );
    lines.push(`  --lx-tracking-${style.name}: ${style.letterSpacing};`);
  }
  for (const step of json.spacing) {
    lines.push(`  --lx-${step.name}: ${step.value};`);
  }
  lines.push(`  --lx-radius: ${json.radiusNone};`);
  lines.push(`  --lx-stroke-hair: ${json.strokeHair};`);
  lines.push(`  --lx-stroke-heavy: ${json.strokeHeavy};`);
  // contracts.md §5.4: layout sizes come from @lattice-studio/tokens as
  // var(--lx-*) too, not only from dist/tokens.ts. Generated from the same
  // `layoutSizes` object as tokens.ts (layout.ts), so the two can't drift.
  for (const key of LAYOUT_CSS_LENGTH_KEYS) {
    lines.push(`  --lx-${kebab(key)}: ${layoutSizes[key]}px;`);
  }
  return `:root {\n${lines.join("\n")}\n}`;
}

function forcedColorsBlock(): string {
  // spec L785-L786: traces use CanvasText, selection and focus Highlight,
  // card borders CanvasText, the dot grid hides. Focus uses `outline`
  // (forced colors strip `box-shadow`).
  //
  // Traces (the sheet's dependency connector lines, ports and junctions:
  // Composer-Final.dc.html's `.seg`/`.port`/`.jct`) use `--lx-border` for
  // their default state and `--lx-accent` when live or selected — see the
  // README's "Traces" note. `--lx-border`, `--lx-border-strong` and
  // `--lx-border-subtle` (card borders, dividers) go to CanvasText;
  // `--lx-accent` and `--lx-border-focus` (selection, focus) go to
  // Highlight. `--lx-accent-line` is a border-family role (composer's
  // toggle-on button border tint, not a trace or a selection indicator),
  // so it goes to CanvasText alongside the other borders, not Highlight.
  const perTheme = THEMES.map(
    (theme) => `  :root[data-theme="${theme}"] {
    --lx-border: CanvasText;
    --lx-border-strong: CanvasText;
    --lx-border-subtle: CanvasText;
    --lx-accent-line: CanvasText;
    --lx-border-focus: Highlight;
    --lx-accent: Highlight;
    --lx-on-accent: HighlightText;
    --lx-dot: transparent;
  }`,
  ).join("\n");
  return `@media (forced-colors: active) {\n${perTheme}\n}`;
}

function moreContrastBlock(): string {
  // spec L785-L786: "More contrast" (prefers-contrast: more) is 2px strokes
  // and stronger borders.
  const perTheme = THEMES.map(
    (theme) => `  :root[data-theme="${theme}"] {
    --lx-border: var(--lx-border-strong);
    --lx-border-subtle: var(--lx-border);
  }`,
  ).join("\n");
  return `@media (prefers-contrast: more) {
  :root {
    --lx-stroke-hair: 2px;
  }
${perTheme}
}`;
}

export function renderCss(json: TokensJson): string {
  const header = `/* Generated by packages/tokens/src/build.ts. Do not edit by hand.
   Role values reconciled from design/tokens.json and
   design/prototype/composer-theme-tokens.css per decision D3 (see
   packages/tokens/README.md for the role table). */\n`;
  const parts = [
    header,
    baseBlock(json),
    ...THEMES.map((theme) => themeBlock(theme, themeRoles(theme))),
    forcedColorsBlock(),
    moreContrastBlock(),
  ];
  return `${parts.join("\n\n")}\n`;
}
