// Renders dist/tokens.ts: the same values as tokens.css, as typed
// constants, plus the layout sizes core and the sheet share. Self-contained
// (no imports) so it works standalone as the package's `.` export.

import { layoutSizes } from "./layout.ts";
import { THEMES, themeRoles } from "./roles.ts";
import type { TokensJson, TypeStyle } from "./tokens-json.ts";

function jsonLiteral(value: unknown): string {
  return JSON.stringify(value);
}

function renderThemeColors(): string {
  const entries = THEMES.map((theme) => `  ${theme}: ${jsonLiteral(themeRoles(theme))} satisfies ThemeColors,`);
  return `export const themeColors: Record<ThemeId, ThemeColors> = {\n${entries.join("\n")}\n};`;
}

function renderTypeScale(styles: readonly TypeStyle[]): string {
  const entries = styles.map((style) => `  ${jsonLiteral(style.name)}: ${jsonLiteral(style)} satisfies TypeStyle,`);
  return `export const typeScale: Record<string, TypeStyle> = {\n${entries.join("\n")}\n};`;
}

function renderSpacing(json: TokensJson): string {
  const entries = json.spacing.map((step) => `  ${jsonLiteral(step.name)}: ${jsonLiteral(step.value)},`);
  return `export const spacing: Record<string, string> = {\n${entries.join("\n")}\n};`;
}

export function renderTokensTs(json: TokensJson): string {
  return `// Generated by packages/tokens/src/build.ts. Do not edit by hand.

export type ThemeId = ${THEMES.map((t) => jsonLiteral(t)).join(" | ")};

export interface ThemeColors {
  readonly ground: string;
  readonly groundWell: string;
  readonly panel: string;
  readonly raised: string;
  readonly sunken: string;
  readonly text: string;
  readonly textMuted: string;
  readonly textFaint: string;
  readonly border: string;
  readonly borderSubtle: string;
  readonly borderStrong: string;
  readonly borderFocus: string;
  readonly accent: string;
  readonly accentStrong: string;
  readonly onAccent: string;
  readonly accentSoft: string;
  readonly accentLine: string;
  readonly dot: string;
  readonly hatch: string;
}

${renderThemeColors()}

export interface TypeStyle {
  readonly name: string;
  readonly family: "sans" | "mono";
  readonly fontSize: string;
  readonly lineHeight: string;
  readonly fontWeight: number;
  readonly letterSpacing: string;
}

${renderTypeScale(json.typeStyles)}

export const fontFamilies = ${jsonLiteral(json.fontFamilies)} as const;

${renderSpacing(json)}

export const radiusNone = ${jsonLiteral(json.radiusNone)} as const;
export const strokeHair = ${jsonLiteral(json.strokeHair)} as const;
export const strokeHeavy = ${jsonLiteral(json.strokeHeavy)} as const;

export interface LayoutSizes {
  readonly grid: number;
  readonly snap: number;
  readonly dragThreshold: number;
  readonly nudgeSmall: number;
  readonly nudgeLarge: number;
  readonly cardWidth: number;
  readonly headerHeight: number;
  readonly rowHeight: number;
  readonly footerHeight: number;
  readonly collapsedRows: number;
  readonly expandThreshold: number;
  readonly compactZoom: number;
  readonly noteWidth: number;
  readonly traceLabelZoom: number;
  readonly edgeZone: number;
}

export const layoutSizes: LayoutSizes = ${jsonLiteral(layoutSizes)};
`;
}
