import pkg from "../package.json" with { type: "json" };

/** The version every export is headed with ("Generated by Lattice Studio 0.0.0", spec L508). */
export const STUDIO_VERSION: string = pkg.version;
